export enum MegaverseItem {
	SPACE = "SPACE",
	POLYANET = "POLYANET",
	RIGHT_COMETH = "RIGHT_COMETH",
	LEFT_COMETH = "LEFT_COMETH",
	UP_COMETH = "UP_COMETH",
	DOWN_COMETH = "DOWN_COMETH",
	WHITE_SOLOON = "WHITE_SOLOON",
	BLUE_SOLOON = "BLUE_SOLOON",
	RED_SOLOON = "RED_SOLOON",
	PURPLE_SOLOON = "PURPLE_SOLOON",
}
